name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push to Docker Hub
        run: |
          timeout 3600 docker buildx build --platform linux/arm64 --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/gpt-home:latest --push .

      - name: Build and push to GHCR
        run: |
          timeout 3600 docker buildx build --platform linux/arm64 --no-cache -t ghcr.io/${{ github.repository_owner }}/gpt-home:latest --push .
